apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: los-backend
spec:
  to:
    kind: Service
    name: los-backend
  port:
    targetPort: http
  tls:
    termination: edge

# Made with Bob
